name: school_secretariat_app
description: "High school secretariat app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  # إدارة الحالة والواجهات
  provider: ^6.1.2
  responsive_framework: ^1.5.1

  # قواعد البيانات المحلية المشفّرة
  sqflite: ^2.3.2
  sqflite_sqlcipher: ^3.1.0
  flutter_secure_storage: ^9.0.0

  # التصدير والطباعة والـ QR Code
  pdf: ^3.10.8
  printing: ^5.11.1
  excel: ^4.0.3
  qr_flutter: ^4.1.0

  # أدوات إضافية
  csv: ^6.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/students.csv